# Generated by Django 2.0.5 on 2018-05-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.FloatField()),
                ('birth', models.DateField()),
                ('is_guest', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access', models.BooleanField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('on_date', models.DateField()),
                ('for_guests', models.BooleanField()),
                ('adult', models.BooleanField()),
                ('weekend', models.BooleanField()),
                ('area', models.ManyToManyField(to='access.Area')),
                ('visited_this_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='access.Area')),
            ],
        ),
    ]
