# Generated by Django 2.0.5 on 2018-05-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    atomic=False

    dependencies = [
        ('access', '0002_auto_20180527_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
    ]
