# Generated by Django 2.0.5 on 2018-05-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20180527_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
