# Generated by Django 2.0.5 on 2018-05-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='adult',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='rules',
            name='for_guests',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='rules',
            name='from_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rules',
            name='on_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rules',
            name='to_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rules',
            name='weekend',
            field=models.NullBooleanField(),
        ),
    ]
